version: '3'

vars:
  PYTHON: .venv/bin/python
  PIP: .venv/bin/python -m pip
  PACKAGE: firipy
  DIST_DIR: dist

silent: false

tasks:
  venv:
    desc: Ensure virtual environment exists
    cmds:
      - test -d .venv || python3 -m venv .venv
      - '{{.PIP}} install --upgrade pip'

  install:
    desc: Install project with dev extras
    deps: [venv]
    cmds:
      - '{{.PIP}} install -e .[dev]'

  lint:
    desc: Run ruff lint checks
    cmds:
      - '{{.PYTHON}} -m ruff check .'

  typecheck:
    desc: Run mypy static type checking
    cmds:
      - '{{.PYTHON}} -m mypy {{.PACKAGE}}'

  test:
    desc: Run test suite
    cmds:
      - '{{.PYTHON}} -m pytest -q'

  qa:
    desc: Run lint, typecheck, and unit tests
    cmds:
      - task: lint
      - task: typecheck
      - task: test

  live-test:
    desc: Run live integration tests (requires API_KEY_FIRI and LIVE_FIRI_TESTS=1)
    cmds:
      - 'test -n "${API_KEY_FIRI}" || (echo "API_KEY_FIRI not set" && exit 1)'
      - 'test "${LIVE_FIRI_TESTS}" = "1" || (echo "Set LIVE_FIRI_TESTS=1 to enable live tests" && exit 1)'
      - '{{.PYTHON}} -m pytest -q tests/test_live_firi.py'

  balance:
    desc: Fetch balances from the live API (requires API_KEY_FIRI)
    cmds:
      - 'test -n "${API_KEY_FIRI}" || (echo "API_KEY_FIRI not set" && exit 1)'
      - '{{.PYTHON}} scripts/check_balance.py'

  build:
    desc: Build sdist and wheel
    cmds:
      - 'rm -rf {{.DIST_DIR}}'
      - '{{.PYTHON}} -m build'

  release-check:
    desc: Run release validation (lint, typecheck, unit tests, build)
    cmds:
      - task: qa
      - task: build

  version:
    desc: Bump semantic version and roll CHANGELOG (PART=patch|minor|major or NEW=x.y.z)
    cmds:
      - |
        PART="{{default \"patch\" .PART}}"
        DRY_FLAG=""
        if [ "{{.DRY_RUN}}" = "1" ]; then DRY_FLAG="--dry-run"; fi
        if [ -n "{{.NEW}}" ]; then
          {{.PYTHON}} scripts/bump_version.py --new-version "{{.NEW}}" ${DRY_FLAG}
        else
          {{.PYTHON}} scripts/bump_version.py --part "${PART}" ${DRY_FLAG}
        fi
